"""
prompt_runner — ** The `scrapyard.llm.prompt_runner` module executes prompts generated by the `prompt_assembler` and validates outputs using `json_output_validator`, ensuring consistent and reliable LLM interaction. 

### PART-META-JSON
{
  "name": "prompt_runner",
  "layer": "llm",
  "purpose": "Executes prompts generated by the `prompt_assembler` and validates outputs using `json_output_validator`, ensuring consistent and reliable LLM interaction.",
  "addition": true,
  "status": "core",
  "dependencies": [],
  "inputs": "Public API: get_execution_log(); run_prompt(prompt, input_data, llm, schema); post_process_output(output, schema); PromptExecutionLog(...).",
  "outputs": "Returns: get_execution_log -> list; run_prompt -> Dict; post_process_output -> Dict.",
  "files_created": [],
  "security_notes": "Pure computation: no network, filesystem, subprocess, secrets, or persistence; validate ranges/values at the call site as usual.",
  "ai_usage": "Import what you need from `scrapyard.llm.prompt_runner`.",
  "example": "from scrapyard.llm.prompt_runner import *",
  "import_path": "scrapyard.llm.prompt_runner"
}
### END-PART-META
"""
from datetime import datetime, timezone
from dataclasses import dataclass, field
from typing import Optional, Dict, Any
import json
import logging
import jsonschema

# Configure logger
logger = logging.getLogger(__name__)

@dataclass
class PromptExecutionLog:
    prompt: str
    input_data: Dict[str, Any]
    output: Optional[Dict[str, Any]]
    error: Optional[str] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

# Execution log kept in memory so runs are inspectable/testable.
_execution_log: list = []


def get_execution_log() -> list:
    return list(_execution_log)


def _render_prompt(prompt: str, input_data: Dict) -> str:
    """Substitute {placeholders} from input_data into the prompt template."""
    try:
        return prompt.format(**input_data)
    except (KeyError, IndexError):
        # unmatched placeholders are left for the model rather than crashing
        return prompt


def run_prompt(prompt: str, input_data: Dict, llm=None,
               schema: Optional[Dict] = None) -> Dict:
    """
    Execute a prompt with the provided input data and validate the output.

    The prompt is rendered with input_data ({placeholder} substitution), sent to
    `llm` (any callable str -> str, or an object with .complete(messages); when
    omitted, the provider resolved by scrapyard.ai.providers is used — real
    HTTPS when keys are configured, deterministic offline stub otherwise), and
    the response is JSON-parsed and validated against `schema` when given.

    :param prompt: The LLM prompt template to execute.
    :param input_data: Input data substituted into the prompt.
    :param llm: Optional executor (callable or client with .complete()).
    :param schema: Optional JSON schema the parsed output must satisfy.
    :return: Validated output as a dictionary.
    """
    rendered = _render_prompt(prompt, input_data or {})
    log_entry = PromptExecutionLog(prompt=rendered, input_data=input_data, output=None)
    try:
        if llm is None:
            from scrapyard.ai.providers import get_provider
            provider = get_provider()
            raw = provider.complete([{"role": "user", "content": rendered}])["content"]
        elif callable(llm):
            raw = llm(rendered)
        elif hasattr(llm, "complete"):
            raw = llm.complete([{"role": "user", "content": rendered}])["content"]
        else:
            raise TypeError("llm must be callable or expose .complete()")

        # Parse: JSON when possible, else wrap the raw text.
        if isinstance(raw, dict):
            output = raw
        else:
            try:
                output = json.loads(raw)
                if not isinstance(output, dict):
                    output = {"result": output}
            except (json.JSONDecodeError, TypeError):
                output = {"result": raw}

        validated_output = post_process_output(output, schema or {})
        log_entry.output = validated_output
        logger.info("Prompt executed successfully.")
        return validated_output
    except ValueError:
        log_entry.error = "schema validation failed"
        raise
    except Exception as e:
        log_entry.error = str(e)
        logger.error(f"Error executing prompt: {prompt}, Input: {input_data}", exc_info=True)
        raise RuntimeError(f"Failed to execute prompt: {str(e)}")
    finally:
        _execution_log.append(log_entry)

def post_process_output(output: Dict, schema: Dict) -> Dict:
    """
    Validate the output against a JSON schema.
    
    :param output: The output from LLM execution.
    :param schema: The JSON schema for validation.
    :return: Validated output as a dictionary.
    :raises ValueError: If the output does not match the schema.
    """
    try:
        jsonschema.validate(instance=output, schema=schema)
        return output
    except jsonschema.exceptions.ValidationError as e:
        raise ValueError(f"Output does not match schema: {e}")

def _selftest():
    schema = {
        "type": "object",
        "properties": {
            "report": {"type": "string"},
            "summary": {"type": "string"},
        },
        "required": ["report", "summary"],
    }

    # 1. Deterministic JSON-emitting executor + schema validation
    def json_llm(rendered: str) -> str:
        assert "sales" in rendered, "input_data must be substituted into the prompt"
        return '{"report": "Q4 numbers", "summary": "up 12%"}'

    out = run_prompt("Generate a report for the {team} team.",
                     {"team": "sales"}, llm=json_llm, schema=schema)
    assert out == {"report": "Q4 numbers", "summary": "up 12%"}

    # 2. Schema violation is rejected
    try:
        run_prompt("x", {}, llm=lambda p: '{"report": "only"}', schema=schema)
        raise AssertionError("expected ValueError for schema violation")
    except ValueError:
        pass

    # 3. Non-JSON output is wrapped, not fabricated
    out2 = run_prompt("say hi", {}, llm=lambda p: "plain text answer")
    assert out2 == {"result": "plain text answer"}

    # 4. Client-object executor (.complete) path — offline LLMClient
    from scrapyard.ai.llm_client import LLMClient
    out3 = run_prompt("question about {topic}", {"topic": "parts"},
                      llm=LLMClient(offline=True))
    assert out3["result"].startswith("[offline:")
    assert "parts" in out3["result"]

    # 5. Failing executor surfaces as RuntimeError and is logged
    try:
        run_prompt("x", {}, llm=lambda p: 1 / 0)
        raise AssertionError("expected RuntimeError")
    except RuntimeError:
        pass
    log = get_execution_log()
    assert len(log) >= 4
    assert any(entry.error for entry in log)
    assert all(isinstance(entry.timestamp, datetime) for entry in log)

    # 6. post_process_output standalone
    assert post_process_output({"a": 1}, {}) == {"a": 1}
    try:
        post_process_output({"a": "x"}, {"type": "object",
                                         "properties": {"a": {"type": "integer"}}})
        raise AssertionError("expected ValueError")
    except ValueError:
        pass

    print("prompt_runner selftest passed")

if __name__ == "__main__":
    _selftest()
