"""
scaling — Horizontal scaling (load balancer config) + CDN readiness (cache headers).

Load balancing (L11) only works if the app is stateless and shared state lives in the
backing services — which Scrapyard already enforces: sessions/jobs in Postgres, cache
+ rate limits in Redis (L9/L10), DB-enforced isolation (L8). So N replicas behind a
balancer behave as one. CDN readiness (L10) means emitting correct Cache-Control so an
edge can serve cacheable responses.

### PART-META-JSON
{
  "name": "scaling",
  "layer": "operations",
  "purpose": "nginx load-balancer config + CDN cache-control middleware for horizontal scale.",
  "addition": true,
  "status": "core",
  "dependencies": [],
  "inputs": "Upstream addresses; cacheable path prefixes + max-age.",
  "outputs": "An nginx upstream/proxy config; a Cache-Control middleware.",
  "files_created": [],
  "security_notes": "Cache-Control is only applied to safe GETs on configured prefixes; never to authenticated/dynamic routes by default.",
  "ai_usage": "from scrapyard.operations.scaling import nginx_loadbalancer_conf, CacheControlMiddleware",
  "example": "app.add_middleware(CacheControlMiddleware, prefixes=['/static'], max_age=3600)",
  "import_path": "scrapyard.operations.scaling"
}
### END-PART-META
"""
from __future__ import annotations

STATUS = "core"


def nginx_loadbalancer_conf(upstreams, *, listen: int = 8080, app_port: int = 8000) -> str:
    """A real nginx config round-robining across `upstreams` (host:port strings).
    Adds X-Upstream so callers can see which backend served a request, and proxies
    /readyz so the balancer can health-gate members."""
    servers = "\n".join(f"        server {u} max_fails=2 fail_timeout=5s;" for u in upstreams)
    return f"""# Generated by Scrapyard — horizontal scaling load balancer
worker_processes auto;
events {{ worker_connections 1024; }}
http {{
    upstream app_backend {{
{servers}
    }}
    server {{
        listen {listen};
        location / {{
            proxy_pass http://app_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Upstream $upstream_addr always;
        }}
        location = /readyz {{
            proxy_pass http://app_backend/readyz;
            add_header X-Upstream $upstream_addr always;
        }}
    }}
}}
"""


class CacheControlMiddleware:
    """ASGI middleware: sets Cache-Control on safe GET responses for configured path
    prefixes, so a CDN/edge can cache them. Dynamic/authenticated routes are untouched."""

    def __init__(self, app, *, prefixes=("/static",), max_age: int = 3600, public: bool = True):
        self.app = app
        self.prefixes = tuple(prefixes)
        self.value = f"{'public' if public else 'private'}, max-age={max_age}"

    async def __call__(self, scope, receive, send):
        if scope.get("type") != "http" or scope.get("method") != "GET" \
                or not scope.get("path", "").startswith(self.prefixes):
            await self.app(scope, receive, send)
            return

        async def send_wrapper(message):
            if message.get("type") == "http.response.start":
                headers = message.setdefault("headers", [])
                if not any(k.lower() == b"cache-control" for k, _ in headers):
                    headers.append((b"cache-control", self.value.encode()))
            await send(message)

        await self.app(scope, receive, send_wrapper)


def _selftest() -> None:
    """Offline self-test: nginx config generation + selective cache-control.

    NOTE: this module's scaling primitives are a load-balancer config generator
    and a CDN cache-control middleware (there is no scale-up/down decision fn to
    exercise), so the self-test targets those actual public surfaces.
    """
    import asyncio

    # 1. nginx config round-robins across the given upstreams and gates on /readyz.
    conf = nginx_loadbalancer_conf(["10.0.0.1:8000", "10.0.0.2:8000"], listen=8080)
    assert "upstream app_backend" in conf
    assert "server 10.0.0.1:8000" in conf and "server 10.0.0.2:8000" in conf, \
        "every upstream must appear in the config"
    assert "listen 8080;" in conf and "/readyz" in conf, "must listen + health-gate"
    # negative: an upstream that was not passed must not appear.
    assert "10.0.0.9" not in conf, "config must not invent upstreams"

    # 2. CacheControlMiddleware sets Cache-Control only on safe GETs to a prefix.
    async def drive(path: str, method: str = "GET"):
        async def downstream(scope, receive, send):
            await send({"type": "http.response.start", "status": 200,
                        "headers": [(b"content-type", b"text/plain")]})
            await send({"type": "http.response.body", "body": b"x"})

        mw = CacheControlMiddleware(downstream, prefixes=("/static",), max_age=3600)
        captured = {}

        async def receive():
            return {"type": "http.request"}

        async def send(msg):
            if msg["type"] == "http.response.start":
                captured["headers"] = msg["headers"]

        await mw({"type": "http", "method": method, "path": path}, receive, send)
        return captured["headers"]

    def has_cc(headers):
        return any(k.lower() == b"cache-control" for k, _ in headers)

    assert has_cc(asyncio.run(drive("/static/app.css"))), \
        "cacheable prefix must receive Cache-Control"
    # negative: a non-configured path is left untouched.
    assert not has_cc(asyncio.run(drive("/api/data"))), \
        "dynamic route must not be cached"
    # negative: a non-GET method is left untouched.
    assert not has_cc(asyncio.run(drive("/static/app.css", method="POST"))), \
        "unsafe method must not be cached"
    print("scaling self-test passed")


if __name__ == "__main__":
    _selftest()
