"""
reports — Persisted report definitions with real generation/export.

### PART-META-JSON
{
  "name": "reports",
  "layer": "analytics",
  "purpose": "CRUD for report definitions (name + JSON config + owner), generation to CSV/JSON bytes, file export, owner-based access policy, and summary reporting over event data.",
  "addition": false,
  "status": "core",
  "dependencies": [
    "sqlalchemy",
    "fastapi"
  ],
  "inputs": "create_report(db, name, config, user_id); get_report/update_report/archive_report(db, report_id); generate_report(db, report_id, format in {csv,json}); export_report(db, report_id, format, output_dir=None); apply_report_policy(report, user).",
  "outputs": "Report ORM rows (table 'analytics_reports'); generated bytes; export file path; Page[Report] listings; summary_report dict.",
  "files_created": [
    "report exports (only when export_report is called; written under output_dir or the system temp dir)"
  ],
  "security_notes": "Access control is apply_report_policy: archived reports and non-owner users are denied - CALLERS must invoke it before get/generate, it is not enforced inside CRUD. Report configs are stored as JSON and never executed or interpolated into SQL. export_report writes files: paths are built from the report id (not the user-supplied name) to prevent path traversal via report names. CSV output escapes quotes; guard against spreadsheet formula injection downstream if configs contain user text.",
  "ai_usage": "Import from `scrapyard.analytics.reports`; call IntPKModel.metadata.create_all(engine) before use; check apply_report_policy before serving a report to a user.",
  "example": "from scrapyard.analytics.reports import create_report, generate_report",
  "import_path": "scrapyard.analytics.reports"
}
### END-PART-META
"""
from typing import List, Dict, Optional, Any, Callable, TypeVar, Generic
from datetime import datetime, timezone
import json
import os
import tempfile

from sqlalchemy import String, Boolean, DateTime, JSON, Integer
from sqlalchemy.orm import Mapped, mapped_column, Session
from sqlalchemy.exc import NoResultFound
from fastapi import HTTPException

from scrapyard.database.base_model import IntPKModel

STATUS = "core"

T = TypeVar('T')


class Page(Generic[T]):
    def __init__(self, items: List[T], total: int):
        self.items = items
        self.total = total


class Report(IntPKModel):
    """Persisted report definition (ORM model - the previous pydantic
    stand-in could not be stored or queried)."""
    __tablename__ = "analytics_reports"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    config: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    owner_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    archived: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc))


class ReportNotFoundError(HTTPException):
    def __init__(self):
        super().__init__(status_code=404, detail="Report not found")


_REPORT_HOOKS: Dict[str, Callable] = {}


def add_report_hook(name: str, callback: Callable) -> None:
    """Register a callback fired with (report, format) after each generation."""
    if not callable(callback):
        raise ValueError("callback must be callable")
    _REPORT_HOOKS[name] = callback


def remove_report_hook(name: str) -> None:
    _REPORT_HOOKS.pop(name, None)


def create_report(db: Session, name: str, config: dict, user_id: int) -> Report:
    if not name:
        raise ValueError("Report name is required")
    report = Report(name=name, config=dict(config or {}), owner_id=user_id)
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


def get_report(db: Session, report_id: int) -> Report:
    try:
        return db.query(Report).filter(Report.id == report_id).one()
    except NoResultFound:
        raise ReportNotFoundError()


def list_reports(db: Session, filters: Optional[Dict[str, Any]] = None, page: int = 1, per_page: int = 20) -> Page[Report]:
    query = db.query(Report)
    if filters:
        for key, value in filters.items():
            if not hasattr(Report, key):
                raise ValueError(f"Unknown report filter: {key}")
            query = query.filter(getattr(Report, key) == value)
    total = query.count()
    reports = query.offset((page - 1) * per_page).limit(per_page).all()
    return Page(items=reports, total=total)


def update_report(db: Session, report_id: int, config: dict) -> Report:
    report = get_report(db, report_id)
    report.config = dict(config or {})
    db.commit()
    db.refresh(report)
    return report


def archive_report(db: Session, report_id: int) -> None:
    report = get_report(db, report_id)
    report.archived = True
    db.commit()


def _csv_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    if any(ch in text for ch in (',', '"', '\n', '\r')):
        return '"' + text.replace('"', '""') + '"'
    return text


def generate_report(db: Session, report_id: int, format: str = "csv") -> bytes:
    """Render the report definition to bytes (csv or json)."""
    report = get_report(db, report_id)
    if format == "json":
        payload = json.dumps(serialize_report(report), indent=2, default=str).encode("utf-8")
    elif format == "csv":
        lines = ["key,value"]
        lines.append(f"name,{_csv_escape(report.name)}")
        lines.append(f"owner_id,{report.owner_id}")
        for key, value in sorted((report.config or {}).items()):
            lines.append(f"{_csv_escape(key)},{_csv_escape(value)}")
        payload = ("\n".join(lines) + "\n").encode("utf-8")
    else:
        raise ValueError(f"Unsupported report format: {format}")

    for hook in list(_REPORT_HOOKS.values()):
        try:
            hook(report, format)
        except Exception:
            import logging
            logging.getLogger(__name__).warning("report hook failed", exc_info=True)
    return payload


def export_report(db: Session, report_id: int, format: str = "csv",
                  output_dir: Optional[str] = None) -> str:
    """Generate the report and write it to disk; returns the real file path.

    The filename is derived from the report id, never from the user-supplied
    name, so report names cannot traverse paths.
    """
    data = generate_report(db, report_id, format)
    directory = output_dir or tempfile.gettempdir()
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, f"report_{report_id}.{format}")
    with open(path, "wb") as fh:
        fh.write(data)
    return path


def serialize_report(report: Report) -> dict:
    return {
        "id": report.id,
        "name": report.name,
        "config": report.config,
        "owner_id": report.owner_id,
        "archived": report.archived,
    }


def bulk_generate_reports(db: Session, report_ids: List[int], format: str = "csv") -> List[bytes]:
    return [generate_report(db, report_id, format) for report_id in report_ids]


def apply_report_policy(report: Report, user: Any) -> bool:
    """Owner-only access; archived reports are closed to everyone."""
    if report.archived:
        return False
    user_id = getattr(user, "id", user)
    return user_id == report.owner_id


# --- grafted from original part (API stability) ---
def summary_report(db):
    from scrapyard.analytics.usage_metrics import active_users, events_by_name
    return {"active_users": active_users(db), "events_by_name": events_by_name(db)}


def _selftest() -> None:
    from sqlalchemy import create_engine
    # Import before create_all so the analytics_events table is registered.
    from scrapyard.analytics.event_tracking import track_event

    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmpdir:
        engine = create_engine(f"sqlite:///{os.path.join(tmpdir, 'test.db')}")
        IntPKModel.metadata.create_all(engine)
        try:
            with Session(engine) as db:
                rep = create_report(db, 'Monthly, "Sales"', {"metric": "revenue", "window": "30d"}, user_id=7)
                assert rep.id is not None and rep.config["metric"] == "revenue"

                fetched = get_report(db, rep.id)
                assert fetched.name == 'Monthly, "Sales"'
                try:
                    get_report(db, 999999)
                    assert False
                except HTTPException as e:
                    assert e.status_code == 404

                # listing + filters
                create_report(db, "Other", {}, user_id=8)
                page = list_reports(db, {"owner_id": 7})
                assert page.total == 1 and page.items[0].id == rep.id
                try:
                    list_reports(db, {"nope": 1})
                    assert False
                except ValueError:
                    pass

                # update
                update_report(db, rep.id, {"metric": "signups"})
                assert get_report(db, rep.id).config == {"metric": "signups"}

                # generation: real content, both formats, hook fires
                fired = []
                add_report_hook("audit", lambda r, f: fired.append((r.id, f)))
                try:
                    csv_bytes = generate_report(db, rep.id, "csv")
                    json_bytes = generate_report(db, rep.id, "json")
                finally:
                    remove_report_hook("audit")
                assert b"metric,signups" in csv_bytes
                assert b'"Monthly, ""Sales"""' in csv_bytes  # csv escaping
                assert json.loads(json_bytes)["config"] == {"metric": "signups"}
                assert fired == [(rep.id, "csv"), (rep.id, "json")]
                try:
                    generate_report(db, rep.id, "xlsx")
                    assert False
                except ValueError:
                    pass

                # export writes a real file derived from the id
                path = export_report(db, rep.id, "csv", output_dir=tmpdir)
                assert os.path.basename(path) == f"report_{rep.id}.csv"
                with open(path, "rb") as fh:
                    assert fh.read() == csv_bytes

                # bulk
                blobs = bulk_generate_reports(db, [rep.id], "json")
                assert len(blobs) == 1 and json.loads(blobs[0])["id"] == rep.id

                # policy: owner-only, archived closed
                class U:
                    def __init__(self, id):
                        self.id = id
                assert apply_report_policy(rep, U(7)) is True
                assert apply_report_policy(rep, U(8)) is False
                archive_report(db, rep.id)
                assert apply_report_policy(get_report(db, rep.id), U(7)) is False

                # summary_report over event data
                track_event(db, "login", user_id=1)
                db.commit()
                summary = summary_report(db)
                assert summary["active_users"] == 1
                assert summary["events_by_name"] == {"login": 1}
        finally:
            engine.dispose()


if __name__ == "__main__":
    _selftest()
    print("reports selftest OK")
