# Generated by Scrapyard — infrastructure (compute + managed data + CDN)
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# L6 compute: container service running the app image behind the load balancer
resource "aws_ecs_cluster" "app" {
  name = "${var.app_name}-cluster"
}

resource "aws_ecs_service" "app" {
  name            = "${var.app_name}-svc"
  cluster         = aws_ecs_cluster.app.id
  desired_count   = var.replicas
  launch_type     = "FARGATE"
}

# L11 load balancing across the replicas
resource "aws_lb" "app" {
  name               = "${var.app_name}-lb"
  load_balancer_type = "application"
}

# L3 managed Postgres (the schema is owned by Alembic migrations)
resource "aws_db_instance" "postgres" {
  identifier        = "${var.app_name}-db"
  engine            = "postgres"
  engine_version    = "16"
  instance_class    = var.db_instance_class
  allocated_storage = 20
  db_name           = "app"
  username          = "app"
  multi_az          = true
}

# L10 managed Redis (cache + distributed rate limiter)
resource "aws_elasticache_cluster" "redis" {
  cluster_id      = "${var.app_name}-redis"
  engine          = "redis"
  node_type       = var.redis_node_type
  num_cache_nodes = 1
}

# L10 CDN in front of the load balancer (honors app Cache-Control headers)
resource "aws_cloudfront_distribution" "cdn" {
  enabled = true
  origin {
    domain_name = aws_lb.app.dns_name
    origin_id   = "${var.app_name}-origin"
  }
  default_cache_behavior {
    target_origin_id       = "${var.app_name}-origin"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
  }
}

output "cdn_domain" {
  value = aws_cloudfront_distribution.cdn.domain_name
}

output "lb_dns" {
  value = aws_lb.app.dns_name
}
