"""Overturn — appeal packet compiler (product-specific glue, ~60 lines).

GET /packet/{claim_id} -> one formatted, chronologically-ordered appeal packet:
claim facts, denial + deadlines, every evidence item (decrypted for its owner),
every logged call with reference numbers, and the appeal history. This is the
document you upload to the insurer's portal or mail to external review.
"""
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session

from scrapyard.database.db_session import get_db
from scrapyard.models.routes import current_user_id
from scrapyard.models import models as M

router = APIRouter()

def _money(cents):
    return f"${(cents or 0)/100:,.2f}"

def _dt(v):
    return str(v)[:10] if v else "—"

@router.get("/packet/{claim_id}", response_class=PlainTextResponse)
def appeal_packet(claim_id: int, db: Session = Depends(get_db),
                  uid: int = Depends(current_user_id)):
    claim = db.get(M.Claim, claim_id)
    if not claim or claim.user_id != uid:
        raise HTTPException(404, "claim not found")
    denials = db.query(M.Denial).filter_by(claim_id=claim_id, user_id=uid).all()
    appeals = db.query(M.Appeal).filter_by(claim_id=claim_id, user_id=uid).all()
    evidence = db.query(M.EvidenceItem).filter_by(claim_id=claim_id, user_id=uid).all()
    calls = db.query(M.CallLog).filter_by(claim_id=claim_id, user_id=uid).all()

    L = [
        "=" * 68,
        "APPEAL PACKET",
        f"Claim {claim.claim_number} — {claim.insurer}",
        "=" * 68,
        "",
        "CLAIM FACTS",
        f"  Service:       {claim.service}",
        f"  Provider:      {claim.provider}",
        f"  Date of svc:   {_dt(claim.service_date)}",
        f"  Amount billed: {_money(claim.billed_cents)}",
        f"  Current state: {claim.status}",
        "",
    ]
    for d in denials:
        L += ["DENIAL",
              f"  Date: {_dt(d.denial_date)}   Reason code: {d.reason_code}",
              f"  Stated reason: {d.reason_text}",
              f"  Internal appeal deadline: {_dt(d.internal_appeal_deadline)}",
              f"  External review deadline: {_dt(d.external_review_deadline)}", ""]
    if appeals:
        L.append("APPEAL HISTORY")
        for a in appeals:
            L += [f"  [{a.level}] filed {_dt(a.filed_at)} — status: {a.status}",
                  f"    Argument: {a.argument}", ""]
    if evidence:
        L.append(f"SUPPORTING EVIDENCE ({len(evidence)} items)")
        for e in sorted(evidence, key=lambda x: str(x.received_at or "")):
            L += [f"  - [{e.kind}] {e.title} (received {_dt(e.received_at)})",
                  f"      {e.body}"]
        L.append("")
    if calls:
        L.append(f"CALL LOG ({len(calls)} calls — reference numbers on file)")
        for c in sorted(calls, key=lambda x: str(x.called_at or "")):
            L += [f"  - {_dt(c.called_at)}  rep: {c.rep_name}  ref#: {c.reference_number}",
                  f"      {c.summary}"]
        L.append("")
    L += ["-" * 68,
          "Every record above is maintained on a tamper-evident audit chain.",
          "Generated by Overturn."]
    return "\n".join(L)
