"""
gen_infra.py — Write infrastructure-as-code for the outer layers (L6/L11/CDN).

These layers are environment, not app code: a load balancer, cloud compute, a CDN.
Scrapyard can WRITE validatable config for them, not provision them. So this emits:
  - deploy/nginx.conf            (L11 load balancer; validated by `nginx -t`)
  - deploy/docker-compose.scale.yml (L11 scaling: nginx in front of N web replicas)
  - deploy/terraform/main.tf     (L6 compute + managed Postgres/Redis + L10 CDN)
  - deploy/terraform/variables.tf
Honest boundary: Terraform is parse-validated (python-hcl2), NOT `terraform apply`-ed.
"""
from __future__ import annotations
import os

from scrapyard.operations.scaling import nginx_loadbalancer_conf


def _compose_scale() -> str:
    return """# Generated by Scrapyard — horizontal scaling overlay
# Usage: docker compose -f docker-compose.yml -f deploy/docker-compose.scale.yml up --scale web=3
services:
  web:
    deploy:
      replicas: 3
  lb:
    image: nginx:1.27
    ports: ["80:8080"]
    volumes: ["./deploy/nginx.conf:/etc/nginx/nginx.conf:ro"]
    depends_on:
      web:
        condition: service_healthy
"""


def _terraform_main() -> str:
    # Provider-agnostic shape using AWS resource names as a concrete example. Declares
    # compute (L6), managed Postgres + Redis (L3 managed), and a CDN (L10).
    return """# Generated by Scrapyard — infrastructure (compute + managed data + CDN)
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# L6 compute: container service running the app image behind the load balancer
resource "aws_ecs_cluster" "app" {
  name = "${var.app_name}-cluster"
}

resource "aws_ecs_service" "app" {
  name            = "${var.app_name}-svc"
  cluster         = aws_ecs_cluster.app.id
  desired_count   = var.replicas
  launch_type     = "FARGATE"
}

# L11 load balancing across the replicas
resource "aws_lb" "app" {
  name               = "${var.app_name}-lb"
  load_balancer_type = "application"
}

# L3 managed Postgres (the schema is owned by Alembic migrations)
resource "aws_db_instance" "postgres" {
  identifier        = "${var.app_name}-db"
  engine            = "postgres"
  engine_version    = "16"
  instance_class    = var.db_instance_class
  allocated_storage = 20
  db_name           = "app"
  username          = "app"
  multi_az          = true
}

# L10 managed Redis (cache + distributed rate limiter)
resource "aws_elasticache_cluster" "redis" {
  cluster_id      = "${var.app_name}-redis"
  engine          = "redis"
  node_type       = var.redis_node_type
  num_cache_nodes = 1
}

# L10 CDN in front of the load balancer (honors app Cache-Control headers)
resource "aws_cloudfront_distribution" "cdn" {
  enabled = true
  origin {
    domain_name = aws_lb.app.dns_name
    origin_id   = "${var.app_name}-origin"
  }
  default_cache_behavior {
    target_origin_id       = "${var.app_name}-origin"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
  }
}

output "cdn_domain" {
  value = aws_cloudfront_distribution.cdn.domain_name
}

output "lb_dns" {
  value = aws_lb.app.dns_name
}
"""


def _terraform_variables() -> str:
    return """variable "app_name"          { type = string  default = "scrapyard-app" }
variable "region"            { type = string  default = "us-east-1" }
variable "replicas"          { type = number  default = 3 }
variable "db_instance_class" { type = string  default = "db.t3.medium" }
variable "redis_node_type"   { type = string  default = "cache.t3.micro" }
"""


def write_infra(out_dir: str) -> dict:
    deploy = os.path.join(out_dir, "deploy")
    tf = os.path.join(deploy, "terraform")
    os.makedirs(tf, exist_ok=True)
    files = {
        "deploy/nginx.conf": nginx_loadbalancer_conf(["web:8000"], listen=8080),
        "deploy/docker-compose.scale.yml": _compose_scale(),
        "deploy/terraform/main.tf": _terraform_main(),
        "deploy/terraform/variables.tf": _terraform_variables(),
    }
    for rel, content in files.items():
        with open(os.path.join(out_dir, rel), "w", encoding="utf-8") as f:
            f.write(content)
    return {"written": list(files)}
