"""
gen_deployment.py — Write a real, internally-consistent deployment for an assembled app.

Not config strings: this writes a runnable Dockerfile + docker-compose.yml + .dockerignore
+ .env.production.example that wire the production backends this stack actually requires
(Postgres, Redis, db-backed jobs, RLS) and a container healthcheck that hits /readyz, so
an orchestrator only routes traffic once migrations are applied and dependencies are up.

The compose `web` service sets the infra-backed env (DATABASE_URL->db, REDIS_URL->redis,
CACHE_BACKEND/RATE_LIMIT_BACKEND=redis, JOBS_BACKEND=db); external secrets live in
.env.production (operator-filled). The validation contract proves the generated config
satisfies the app's own fail-closed production gate.
"""
from __future__ import annotations
import os

PORT = 8000
# python readiness check; single-quoted URL so it nests cleanly in shell and YAML
_HC_CODE = ("import urllib.request,sys; "
            "sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/readyz').status==200 else 1)")


def _dockerfile() -> str:
    return f"""# Generated by Scrapyard — production image
FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN useradd -m appuser && chown -R appuser /app
USER appuser
EXPOSE {PORT}
# /readyz is fail-closed: 200 only when DB reachable AND migrations at head
HEALTHCHECK --interval=10s --timeout=3s --start-period=30s --retries=12 CMD python -c "{_HC_CODE}"
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{PORT}"]
"""


def _compose() -> str:
    return f"""# Generated by Scrapyard — production stack (app + postgres + redis)
services:
  web:
    build: .
    ports: ["{PORT}:{PORT}"]
    env_file: [.env.production]
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      REDIS_URL: redis://redis:6379/0
      CACHE_BACKEND: redis
      RATE_LIMIT_BACKEND: redis
      JOBS_BACKEND: db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "{_HC_CODE}"]
      interval: 10s
      timeout: 3s
      retries: 12
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 12
  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12
volumes:
  pgdata:
"""


def _env_production_example() -> str:
    # Infra vars come from docker-compose.yml; these are the external secrets the
    # operator must supply. Values here are placeholders that pass the prod gate.
    return (
        "# Fill these before `docker compose up`. Infra vars (DATABASE_URL, REDIS_URL,\n"
        "# CACHE_BACKEND, RATE_LIMIT_BACKEND, JOBS_BACKEND) are set by docker-compose.yml.\n"
        "SECRET_KEY=change-me-to-a-long-random-string\n"
        "SCRAPYARD_CRYPTO_BACKEND=citadel\n"
        "SCRAPYARD_RLS=enforce\n"
        "SMTP_HOST=smtp.example.com\n"
        "SCRAPYARD_LLM_PROVIDER=openai\n"
        "OPENAI_API_KEY=set-your-key\n"
        "SENTRY_DSN=\n"
        "OTEL_EXPORTER_OTLP_ENDPOINT=\n"
    )


def _dockerignore() -> str:
    return "__pycache__/\n*.pyc\n.env\n.env.*\n!.env.production.example\n.git/\n*.db\n"


# Env the compose `web` service provides (infra-backed), used by the validator.
COMPOSE_WEB_ENV = {
    "APP_ENV": "production",
    "DATABASE_URL": "postgresql+psycopg2://app:app@db:5432/app",
    "REDIS_URL": "redis://redis:6379/0",
    "CACHE_BACKEND": "redis",
    "RATE_LIMIT_BACKEND": "redis",
    "JOBS_BACKEND": "db",
}


def _app_ci_workflow() -> str:
    return """name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U app -d app"
          --health-interval 5s --health-timeout 3s --health-retries 12
      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s --health-timeout 3s --health-retries 12
    env:
      PYTHONPATH: .
      APP_ENV: development
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install
        run: pip install -r requirements.txt
      - name: Smoke (boots + mounts routes)
        run: python smoke_check.py
      - name: Behavior (feature routes work)
        run: python behavior_check.py
      - name: Migrations apply on real Postgres
        env:
          DATABASE_URL: postgresql+psycopg2://app:app@localhost:5432/app
        run: alembic upgrade head
      - name: Build the production image
        run: docker build -t app-image .
"""


def write_deployment(out_dir: str) -> dict:
    """Write the deployment files into an assembled app and ensure the prod drivers
    (psycopg2, redis) are in requirements. Returns the files written."""
    files = {
        "Dockerfile": _dockerfile(),
        "docker-compose.yml": _compose(),
        ".dockerignore": _dockerignore(),
        ".env.production.example": _env_production_example(),
    }
    for name, content in files.items():
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as f:
            f.write(content)
    # CI workflow for the generated product
    wf_dir = os.path.join(out_dir, ".github", "workflows")
    os.makedirs(wf_dir, exist_ok=True)
    with open(os.path.join(wf_dir, "ci.yml"), "w", encoding="utf-8") as f:
        f.write(_app_ci_workflow())
    files[".github/workflows/ci.yml"] = "ci"
    # production talks to Postgres + Redis -> ensure the drivers are present
    req_path = os.path.join(out_dir, "requirements.txt")
    reqs = set(l.strip() for l in open(req_path, encoding="utf-8")) if os.path.exists(req_path) else set()
    reqs |= {"psycopg2-binary", "redis", "uvicorn", "fastapi"}
    open(req_path, "w", encoding="utf-8").write("\n".join(sorted(r for r in reqs if r)) + "\n")
    return {"written": list(files)}
