CAPABILITIES = {'template': 'internal_tool',
 'bootable': True,
 'included_parts': ['scrapyard.admin.admin_routes',
                    'scrapyard.admin.audit_logs',
                    'scrapyard.admin.dashboards',
                    'scrapyard.admin.impersonation',
                    'scrapyard.admin.user_management',
                    'scrapyard.analytics.usage_metrics',
                    'scrapyard.api.app_factory',
                    'scrapyard.api.error_handling',
                    'scrapyard.api.request_context',
                    'scrapyard.authorization.admin_access',
                    'scrapyard.authorization.permissions',
                    'scrapyard.authorization.roles',
                    'scrapyard.database.base_model',
                    'scrapyard.database.db_session',
                    'scrapyard.database.pagination',
                    'scrapyard.database.repository',
                    'scrapyard.database.timestamps',
                    'scrapyard.foundation.config',
                    'scrapyard.foundation.error_taxonomy',
                    'scrapyard.foundation.health',
                    'scrapyard.foundation.logging_setup',
                    'scrapyard.frontend.forms',
                    'scrapyard.frontend.tables',
                    'scrapyard.identity.jwt_manager',
                    'scrapyard.identity.password_hashing',
                    'scrapyard.identity.session_manager',
                    'scrapyard.identity.users',
                    'scrapyard.security.rate_limiting',
                    'scrapyard.security.security_headers'],
 'routes': ['/health', '/capabilities', '/admin'],
 'feature_routes': ['/admin'],
 'feature_routes_count': 1,
 'behavior_checks': ['feature_routes_present'],
 'missing_expected_routes': [],
 'local_only_fallbacks': ['security.local_crypto_backend',
                          'communication.email_console',
                          'ai.offline_provider',
                          'jobs.memory_queue'],
 'production_ready': False}
